name: PowerShell Analysis

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:
  pull_request:
    paths:
      - '**/*.ps1'

jobs:
  scan-all:
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install PSScriptAnalyzer
        run: pwsh -Command "Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser"

      - name: Analyze all .ps1 scripts
        run: pwsh -Command "Invoke-ScriptAnalyzer -Path . -Recurse -ReportSummary"

  scan-pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Install PSScriptAnalyzer
        run: pwsh -Command "Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser"

      - name: Fetch base branch
        run: git fetch origin ${{ github.event.pull_request.base.ref }}

      - name: Analyze only modified/added/renamed .ps1 files and comment on PR
        env:
          GITHUB_TOKEN: ${{ secrets.AWSR }}
        run: |
          FILES=$(git diff --name-status origin/${{ github.event.pull_request.base.ref }}...HEAD | grep -E '^[AMR]' | awk '{print $NF}' | grep '\.ps1$' | xargs)
          if [ -n "$FILES" ]; then
            pwsh -Command "Invoke-ScriptAnalyzer -Path $FILES -Recurse | ConvertTo-Json -Depth 5" > psa_result.json
            # Format JSON as markdown table or code block (simple version below)
            echo '## PSScriptAnalyzer Results' > psa_result.md
            if [ -s psa_result.json ]; then
              echo '\n```json' >> psa_result.md
              cat psa_result.json >> psa_result.md
              echo '```' >> psa_result.md
            else
              echo 'No issues detected.' >> psa_result.md
            fi
            # Comment the results on the PR
            gh pr comment ${{ github.event.pull_request.number }} \
              --body-file psa_result.md
          else
            echo "No PowerShell (.ps1) scripts were modified, added or renamed in this PR."
          fi
        shell: bash
