name: PowerShell Analysis

on:
  schedule:
    - cron: '0 8 * * *'           # Every day at 8am UTC
  workflow_dispatch:               # Manual trigger
  pull_request:
    paths:
      - '**/*.ps1'                 # PRs that touch .ps1 files

jobs:
  scan-all:
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install PSScriptAnalyzer
        run: pwsh -Command "Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser"

      - name: Analyze all .ps1 scripts
        run: pwsh -Command "Invoke-ScriptAnalyzer -Path . -Recurse -ReportSummary"

  scan-pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Install PSScriptAnalyzer
        run: pwsh -Command "Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser"

      - name: Analyze only modified/added/renamed .ps1 files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          FILES=$(git diff --name-status origin/${{ github.base_ref }}...${{ github.head_ref }} | grep -E '^[AMR]' | awk '{print $NF}' | grep '\.ps1$' | xargs)
          if [ -n "$FILES" ]; then
            pwsh -Command "Invoke-ScriptAnalyzer -Path $FILES -ReportSummary"
          else
            echo "No PowerShell (.ps1) scripts were modified, added or renamed in this PR."
          fi
        shell: bash
