name: Update Credits List

on:
  pull_request:
    types: [closed]
    branches: [master]

  schedule:
    - cron: '0 8 * * *'  # Tous les jours à 8h UTC

  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry run (no commit)'
        required: false
        default: 'false'

jobs:
  update_credits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build new CREDITS.md content
        id: build
        shell: bash
        run: |
          #!/usr/bin/env bash

          echo "Collecting commit data..."

          git fetch --all
          git log --pretty=format:'%H|%an|%ae|%ad' --date=iso --reverse > commits_full.log

          declare -A commit_count
          declare -A last_date
          declare -A last_hash

          while IFS='|' read -r hash name email date; do
            if [[ -z "$name" || -z "$email" || -z "$date" ]]; then
              continue
            fi

            # Determine GitHub profile
            if [[ "$email" =~ \+.*@users\.noreply\.github\.com$ ]]; then
              username="@${email%%+*}"
              username=${username#*@}
              username="@${username}"
            elif [[ "$email" =~ ^[0-9]+@users\.noreply\.github\.com$ ]]; then
              username="@${email%%@*}"
            else
              username="@unknown"
            fi

            key="$name|$username"
            ((commit_count["$key"]++))

            # Keep latest date and hash
            if [[ -z "${last_date["$key"]}" || "$date" > "${last_date["$key"]}" ]]; then
              last_date["$key"]="$date"
              last_hash["$key"]="$hash"
            fi

          done < commits_full.log

          temp="CREDITS.tmp"
          echo "" > "$temp"

          for key in "${!commit_count[@]}"; do
            IFS='|' read -r name username <<< "$key"
            date="${last_date[$key]}"
            hash="${last_hash[$key]}"
            total="${commit_count[$key]}"
            file=$(git show --quiet --pretty=format: --name-only "$hash" | head -n 1)
            [[ -z "$file" ]] && file="/unknown" || file="/$file"

            date_fmt=$(date -d "$date" +"%Y-%m-%d %H:%M")

            echo "| $name | $username | $date_fmt | $total | $file |" >> "$temp"
          done

          sort -r -k3 "$temp" > "$temp.sorted"

          {
            echo "# Credits"
            echo ""
            echo "| Contributor | Profile | Last Commit Date | Total Commits | Last Description/Path |"
            echo "|-------------|---------|------------------|----------------|-------------------------|"
            cat "$temp.sorted"
            echo ""
            echo "<!-- This file is automatically updated by workflow. Additions will appear below. -->"
          } > CREDITS.md

      - name: Show diff
        run: git diff CREDITS.md || true

      - name: Commit and push if not dry-run
        if: github.event.inputs.dry_run != 'true'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          if git diff --quiet; then
            echo "No changes to commit."
          else
            git add CREDITS.md
            git commit -m "Automated update of CREDITS.md"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.AWSR }}
